# Generated by Django 5.1.4 on 2025-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_uuid_alter_productimages_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product_image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
